# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.v1 import agent_pb2 as agent_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """AgentService 仅供内部服务调用，禁止直接暴露给最终用户。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnswerQuestion = channel.unary_unary(
                '/agent.v1.AgentService/AnswerQuestion',
                request_serializer=agent_dot_v1_dot_agent__pb2.AnswerQuestionRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.AnswerQuestionResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/agent.v1.AgentService/GetHealth',
                request_serializer=agent_dot_v1_dot_agent__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """AgentService 仅供内部服务调用，禁止直接暴露给最终用户。
    """

    def AnswerQuestion(self, request, context):
        """执行带权限过滤的 RAG 流程，并按 request_id 幂等保存回答。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """向 Gateway 返回浅层健康状态。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnswerQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerQuestion,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.AnswerQuestionRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.AnswerQuestionResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=agent_dot_v1_dot_agent__pb2.HealthRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """AgentService 仅供内部服务调用，禁止直接暴露给最终用户。
    """

    @staticmethod
    def AnswerQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentService/AnswerQuestion',
            agent_dot_v1_dot_agent__pb2.AnswerQuestionRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.AnswerQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentService/GetHealth',
            agent_dot_v1_dot_agent__pb2.HealthRequest.SerializeToString,
            agent_dot_v1_dot_agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
