# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent/v1/agent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agent/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61gent/v1/agent.proto\x12\x08\x61gent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n\x15\x41nswerQuestionRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x04 \x01(\t\x12\x10\n\x08question\x18\x05 \x01(\t\x12\x10\n\x08trace_id\x18\x06 \x01(\t\x12\x1a\n\x12knowledge_base_ids\x18\x07 \x03(\t\x12\x0f\n\x07\x63hannel\x18\x08 \x01(\t\"\xd5\x01\n\x16\x41nswerQuestionResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12%\n\tcitations\x18\x03 \x03(\x0b\x32\x12.agent.v1.Citation\x12\x0f\n\x07refused\x18\x04 \x01(\x08\x12\x16\n\x0erefusal_reason\x18\x05 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x06 \x01(\t\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xb6\x01\n\x08\x43itation\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x18\n\x10\x64ocument_version\x18\x03 \x01(\x05\x12\r\n\x05title\x18\x04 \x01(\t\x12\x14\n\x0clocator_type\x18\x05 \x01(\t\x12\x15\n\rlocator_value\x18\x06 \x01(\t\x12\x30\n\x0c\x65\x66\x66\x65\x63tive_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\xa3\x01\n\x0c\x41gentService\x12S\n\x0e\x41nswerQuestion\x12\x1f.agent.v1.AnswerQuestionRequest\x1a .agent.v1.AnswerQuestionResponse\x12>\n\tGetHealth\x12\x17.agent.v1.HealthRequest\x1a\x18.agent.v1.HealthResponseB&Z$workchat_bot/gen/go/agent/v1;agentv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$workchat_bot/gen/go/agent/v1;agentv1'
  _globals['_ANSWERQUESTIONREQUEST']._serialized_start=68
  _globals['_ANSWERQUESTIONREQUEST']._serialized_end=253
  _globals['_ANSWERQUESTIONRESPONSE']._serialized_start=256
  _globals['_ANSWERQUESTIONRESPONSE']._serialized_end=469
  _globals['_CITATION']._serialized_start=472
  _globals['_CITATION']._serialized_end=654
  _globals['_HEALTHREQUEST']._serialized_start=656
  _globals['_HEALTHREQUEST']._serialized_end=671
  _globals['_HEALTHRESPONSE']._serialized_start=673
  _globals['_HEALTHRESPONSE']._serialized_end=722
  _globals['_AGENTSERVICE']._serialized_start=725
  _globals['_AGENTSERVICE']._serialized_end=888
# @@protoc_insertion_point(module_scope)
